name: Fernweh
favicon: null
layout_spectrum: 0.24759
typography_spectrum: 0.3549958330113441
title: Fernweh Mods
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8184597303625196
  lightness: 0.7678835256956518
  saturation: 0.16107556340284646
  rhythmicContrast: 0.3354167747311294
purpose: []
